[repository]
authors = ["Moritz Gleissner", "Yusuf Duran"]
name = "Hyprhook"
commit_pins = [
  [
    "293e687389a19b369f312c5c335c9afe7c886be1",
    "bf99dc6ea9558011bfe40f31e8435b59ba031e5d",
  ],
  [
    "19fb13e6cf7c9125b471780156fc423118914fb7",
    "571d45b08678cb7ffc629fb8a4ce43babc80f3a8",
  ],
  [
    "8412ffcc42012888757cd00a004871e8bc353cf2",
    "2510092db845384a5ee66ac3dfe40ea71a15fe43",
  ],
  [
    "5ee35f914f921e5696030698e74fb5566a804768", # hyprland v.0.48
    "cb08b5ca89d81c5497c8fba1a438d435786462f6", # hyprhook
  ],
  [
    "9958d297641b5c84dcff93f9039d80a5ad37ab00", # hyprland v.0.49
    "b65edf5382d657ee1fca18c63d315016a8f599b3",
  ],
  [
    "46174f78b374b6cea669c48880877a8bdcf7802f", # hyprland v.0.51
    "4ce2ecddad0ce2ffad77ea95ea6e8c4591573e5f",
  ],
]

[Hyprhook]
authors = ["Moritz Gleissner", "Yusuf Duran"]
description = "Execute binarys on hyprland events"
output = "hyprhook/hyprhook.so"
build = ["make -C hyprhook all"]
